language: python
python:
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
  - choco install python --version 3.5
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - flake8 .


